import type { Video } from "../storageService";

const GENERATED_XML_COMMENT =
  "<!-- Generated by MyTube. Manual edits may be overwritten. -->";

function escapeXml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/\"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

function appendTag(
  lines: string[],
  tag: string,
  value: string | number | undefined | null
): void {
  if (value === undefined || value === null) {
    return;
  }
  lines.push(`  <${tag}>${escapeXml(String(value))}</${tag}>`);
}

function normalizeDateToDay(value: string | undefined): string | undefined {
  if (!value) {
    return undefined;
  }

  if (/^\d{8}$/.test(value)) {
    return `${value.slice(0, 4)}-${value.slice(4, 6)}-${value.slice(6, 8)}`;
  }

  if (/^\d{4}-\d{2}-\d{2}$/.test(value)) {
    return value;
  }

  const parsed = new Date(value);
  if (Number.isNaN(parsed.getTime())) {
    return undefined;
  }

  return parsed.toISOString().slice(0, 10);
}

function normalizeRuntimeMinutes(duration: string | undefined): string | undefined {
  if (!duration) {
    return undefined;
  }

  const seconds = Number(duration);
  if (!Number.isFinite(seconds) || seconds <= 0) {
    return undefined;
  }

  return String(Math.max(1, Math.ceil(seconds / 60)));
}

export function normalizeShowIdentifier(showRootName: string): string {
  return showRootName
    .trim()
    .toLowerCase()
    .replace(/[\\/]+/g, "-")
    .replace(/\s+/g, "-")
    .replace(/[^a-z0-9-]/g, "")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "") || "show";
}

export interface EpisodeNfoInput {
  video: Video;
  showTitle: string;
  seasonNumber?: number;
  episodeNumber?: number;
  thumbFilename?: string;
}

export function buildEpisodeNfo(input: EpisodeNfoInput): string {
  const { video, showTitle, seasonNumber, episodeNumber, thumbFilename } = input;
  const airedDate = normalizeDateToDay(video.date);
  const runtime = normalizeRuntimeMinutes(video.duration);
  const lines = [GENERATED_XML_COMMENT, "<episodedetails>"];

  appendTag(lines, "title", video.title || "Untitled");
  appendTag(lines, "showtitle", showTitle);
  appendTag(lines, "plot", video.description || "");
  appendTag(lines, "season", seasonNumber);
  appendTag(lines, "episode", episodeNumber);
  appendTag(lines, "aired", airedDate);
  appendTag(lines, "premiered", airedDate);
  appendTag(lines, "dateadded", video.addedAt);
  appendTag(lines, "runtime", runtime);
  appendTag(lines, "studio", video.author || undefined);

  if (Array.isArray(video.tags)) {
    for (const tag of video.tags) {
      appendTag(lines, "tag", tag);
    }
  }

  const videoId = `mytube:video:${video.id}`;
  appendTag(lines, "id", videoId);
  lines.push(
    `  <uniqueid type="mytube" default="true">${escapeXml(videoId)}</uniqueid>`
  );
  appendTag(lines, "thumb", thumbFilename);
  lines.push("</episodedetails>");

  return `${lines.join("\n")}\n`;
}

export interface ShowNfoInput {
  showTitle: string;
  plot: string;
  premiered?: string;
  studio?: string;
}

export function buildShowNfo(input: ShowNfoInput): string {
  const { showTitle, plot, premiered, studio } = input;
  const showId = `mytube:show:${normalizeShowIdentifier(showTitle)}`;
  const lines = [GENERATED_XML_COMMENT, "<tvshow>"];

  appendTag(lines, "title", showTitle);
  appendTag(lines, "sorttitle", showTitle);
  appendTag(lines, "plot", plot);
  appendTag(lines, "premiered", premiered);
  appendTag(lines, "studio", studio);
  appendTag(lines, "id", showId);
  lines.push(
    `  <uniqueid type="mytube" default="true">${escapeXml(showId)}</uniqueid>`
  );
  lines.push("</tvshow>");

  return `${lines.join("\n")}\n`;
}

export function normalizeVideoDateToDay(
  value: string | undefined
): string | undefined {
  return normalizeDateToDay(value);
}
