import path from "path";
import { VIDEOS_DIR } from "../../config/paths";
import { logger } from "../../utils/logger";
import {
  lstatSafeSync,
  pathExistsSafeSync,
  readFileSafeSync,
  readdirSafeSync,
  resolveSafeChildPath,
  unlinkSafeSync,
} from "../../utils/security";
import { removeEmptyDirectoryChain } from "../storageService/fileHelpers";
import type { Video } from "../storageService/types";
import { planMediaServerExportPaths } from "./pathPlanner";

const SWEEP_LIST_LIMIT = 200;
const MYTUBE_NFO_MARKER = "Generated by MyTube";
const MYTUBE_UNIQUE_ID_MARKER = '<uniqueid type="mytube"';
// MyTube-authored sidecars are small (NFOs are well under 1 MB; even a rich
// yt-dlp info.json stays in the low MBs). The `_mytube` marker sits at the end
// of the JSON envelope, so we cannot bound the read to a prefix. Instead we
// refuse to load anything larger than a MyTube sidecar would plausibly be. An
// oversized file is conservatively treated as not-ours and left in place.
const MAX_MARKER_READ_BYTES = 8 * 1024 * 1024;

export interface OrphanArtifactSweepResult {
  sweptFiles: number;
  sweptList: string[];
}

function toDisplayPath(targetPath: string): string {
  return path.relative(VIDEOS_DIR, targetPath).split(path.sep).join("/");
}

function addExpectedPath(expected: Set<string>, targetPath?: string): void {
  if (targetPath) {
    expected.add(path.normalize(targetPath));
  }
}

function buildExpectedArtifactPaths(allVideos: Video[]): Set<string> {
  const expected = new Set<string>();

  for (const video of allVideos) {
    const plan = planMediaServerExportPaths(video);
    if (!plan || !pathExistsSafeSync(plan.videoAbsolutePath, VIDEOS_DIR)) {
      continue;
    }

    addExpectedPath(expected, plan.episodeNfoAbsolutePath);
    addExpectedPath(expected, plan.episodeSourceJsonAbsolutePath);
    addExpectedPath(expected, plan.episodeThumbAliasAbsolutePath);
    addExpectedPath(expected, plan.showNfoAbsolutePath);
    for (const posterPath of plan.showPosterAbsolutePaths) {
      addExpectedPath(expected, posterPath);
    }
  }

  return expected;
}

function walkFiles(rootDir: string): string[] {
  const files: string[] = [];
  const names = readdirSafeSync(rootDir, VIDEOS_DIR);

  for (const name of names) {
    const absolutePath = resolveSafeChildPath(rootDir, name);
    const stat = lstatSafeSync(absolutePath, VIDEOS_DIR);
    if (stat.isSymbolicLink()) {
      continue;
    }
    if (stat.isDirectory()) {
      files.push(...walkFiles(absolutePath));
      continue;
    }
    if (stat.isFile()) {
      files.push(absolutePath);
    }
  }

  return files;
}

function isCandidateFile(targetPath: string): boolean {
  const filename = path.basename(targetPath).toLowerCase();
  return (
    filename.endsWith(".nfo") ||
    filename.endsWith(".info.json") ||
    filename.endsWith("-thumb.jpg") ||
    filename === "show.jpg" ||
    filename === "poster.jpg" ||
    filename === "folder.jpg"
  );
}

function isWithinMarkerReadLimit(targetPath: string): boolean {
  try {
    return lstatSafeSync(targetPath, VIDEOS_DIR).size <= MAX_MARKER_READ_BYTES;
  } catch {
    return false;
  }
}

function isMytubeGeneratedNfo(targetPath: string): boolean {
  if (!isWithinMarkerReadLimit(targetPath)) {
    return false;
  }
  try {
    const contents = readFileSafeSync(targetPath, VIDEOS_DIR, "utf8");
    return (
      contents.includes(MYTUBE_NFO_MARKER) ||
      contents.includes(MYTUBE_UNIQUE_ID_MARKER)
    );
  } catch {
    return false;
  }
}

function isMytubeGeneratedSourceJson(targetPath: string): boolean {
  if (!isWithinMarkerReadLimit(targetPath)) {
    return false;
  }
  try {
    const contents = readFileSafeSync(targetPath, VIDEOS_DIR, "utf8");
    const parsed = JSON.parse(contents) as {
      _mytube?: { generatedBy?: unknown };
    };
    return parsed._mytube?.generatedBy === "mytube";
  } catch {
    return false;
  }
}

function getPairedEpisodeNfoPath(thumbPath: string): string {
  const filename = path.basename(thumbPath);
  return resolveSafeChildPath(
    path.dirname(thumbPath),
    `${filename.slice(0, -"-thumb.jpg".length)}.nfo`
  );
}

function deleteSweptFile(
  targetPath: string,
  result: OrphanArtifactSweepResult
): void {
  if (!pathExistsSafeSync(targetPath, VIDEOS_DIR)) {
    return;
  }

  unlinkSafeSync(targetPath, VIDEOS_DIR);
  removeEmptyDirectoryChain(path.dirname(targetPath), VIDEOS_DIR);
  result.sweptFiles += 1;
  if (result.sweptList.length < SWEEP_LIST_LIMIT) {
    result.sweptList.push(toDisplayPath(targetPath));
  }
  logger.info("Swept orphan media server artifact", {
    path: toDisplayPath(targetPath),
  });
}

export function sweepOrphanMediaServerArtifacts(
  allVideos: Video[]
): OrphanArtifactSweepResult {
  const result: OrphanArtifactSweepResult = {
    sweptFiles: 0,
    sweptList: [],
  };

  try {
    if (!pathExistsSafeSync(VIDEOS_DIR, VIDEOS_DIR)) {
      return result;
    }

    const expected = buildExpectedArtifactPaths(allVideos);
    const candidates = walkFiles(VIDEOS_DIR)
      .filter(isCandidateFile)
      .filter((targetPath) => !expected.has(path.normalize(targetPath)));
    const nfoToDelete = new Set<string>();
    const filesToDelete = new Set<string>();

    for (const targetPath of candidates) {
      const filename = path.basename(targetPath).toLowerCase();
      if (filename.endsWith(".nfo") && isMytubeGeneratedNfo(targetPath)) {
        nfoToDelete.add(path.normalize(targetPath));
        filesToDelete.add(path.normalize(targetPath));
      } else if (
        filename.endsWith(".info.json") &&
        isMytubeGeneratedSourceJson(targetPath)
      ) {
        filesToDelete.add(path.normalize(targetPath));
      }
    }

    for (const targetPath of candidates) {
      const filename = path.basename(targetPath).toLowerCase();
      if (
        filename.endsWith("-thumb.jpg") &&
        nfoToDelete.has(path.normalize(getPairedEpisodeNfoPath(targetPath)))
      ) {
        filesToDelete.add(path.normalize(targetPath));
      } else if (
        (filename === "show.jpg" ||
          filename === "poster.jpg" ||
          filename === "folder.jpg") &&
        nfoToDelete.has(
          path.normalize(
            resolveSafeChildPath(path.dirname(targetPath), "tvshow.nfo")
          )
        )
      ) {
        filesToDelete.add(path.normalize(targetPath));
      }
    }

    for (const targetPath of Array.from(filesToDelete).sort()) {
      deleteSweptFile(targetPath, result);
    }
  } catch (error) {
    logger.error("Failed to sweep orphan media server artifacts", error);
  }

  return result;
}
