type CookiePair = {
  name: string;
  value: string;
};

const NETSCAPE_HEADER = "# Netscape HTTP Cookie File";
const GENERATED_COMMENT =
  "# Generated by MyTube from an HTTP Cookie header.";

const BILIBILI_COOKIE_NAMES = new Set([
  "SESSDATA",
  "bili_jct",
  "DedeUserID",
  "DedeUserID__ckMd5",
  "buvid3",
  "buvid4",
  "CURRENT_FNVAL",
  "CURRENT_QUALITY",
  "b_nut",
  "sid",
]);

const YOUTUBE_COOKIE_NAMES = new Set([
  "VISITOR_INFO1_LIVE",
  "VISITOR_PRIVACY_METADATA",
  "LOGIN_INFO",
  "PREF",
  "YSC",
  "SID",
  "HSID",
  "SSID",
  "APISID",
  "SAPISID",
  "SIDCC",
]);

export class UnsupportedCookieFormatError extends Error {
  constructor() {
    super(
      "Unsupported cookies format. Upload a Netscape-format cookies.txt file, or a YouTube/Bilibili Cookie header."
    );
    this.name = "UnsupportedCookieFormatError";
  }
}

function stripUtf8Bom(content: string): string {
  return content.charCodeAt(0) === 0xfeff ? content.slice(1) : content;
}

function getCookieDataLines(content: string): string[] {
  return stripUtf8Bom(content)
    .split(/\r?\n/)
    .map((line) => line.trimEnd())
    .filter((line) => {
      const trimmed = line.trim();
      return (
        trimmed !== "" &&
        (!trimmed.startsWith("#") || trimmed.startsWith("#HttpOnly_"))
      );
    });
}

function isBooleanField(value: string): boolean {
  const normalized = value.toUpperCase();
  return normalized === "TRUE" || normalized === "FALSE";
}

function isValidNetscapeCookieLine(line: string): boolean {
  const parts = line.split("\t");
  if (parts.length < 7) {
    return false;
  }

  const domain = parts[0].replace(/^#HttpOnly_/, "");
  const [, includeSubdomains, cookiePath, secure, expires, name] = parts;

  return (
    domain.length > 0 &&
    isBooleanField(includeSubdomains) &&
    cookiePath.startsWith("/") &&
    isBooleanField(secure) &&
    /^-?\d+$/.test(expires) &&
    name.length > 0
  );
}

export function isValidNetscapeCookiesFile(content: string): boolean {
  const lines = getCookieDataLines(content);
  return lines.length > 0 && lines.every(isValidNetscapeCookieLine);
}

function extractHeaderValue(content: string, headerName: string): string | null {
  const headerPrefix = `${headerName.toLowerCase()}:`;
  for (const line of stripUtf8Bom(content).split(/\r?\n/)) {
    const trimmed = line.trim();
    if (trimmed.toLowerCase().startsWith(headerPrefix)) {
      return trimmed.slice(headerPrefix.length).trim();
    }
  }
  return null;
}

function extractHost(content: string): string | null {
  const host =
    extractHeaderValue(content, "host") ?? extractHeaderValue(content, ":authority");
  if (host) {
    return host;
  }

  const source =
    extractHeaderValue(content, "origin") ?? extractHeaderValue(content, "referer");
  if (!source) {
    return null;
  }

  try {
    return new URL(source).hostname;
  } catch {
    return null;
  }
}

function isHostOrSubdomain(host: string, domain: string): boolean {
  return host === domain || host.endsWith(`.${domain}`);
}

function normalizeDomainFromHost(host: string): string | null {
  const normalizedHost = host
    .trim()
    .toLowerCase()
    .replace(/:\d+$/, "")
    .replace(/^\.+/, "");

  if (!normalizedHost || normalizedHost === "localhost") {
    return null;
  }

  if (isHostOrSubdomain(normalizedHost, "youtube.com")) {
    return ".youtube.com";
  }
  if (isHostOrSubdomain(normalizedHost, "bilibili.com")) {
    return ".bilibili.com";
  }

  return `.${normalizedHost.replace(/^www\./, "")}`;
}

function extractCookieHeader(content: string): string {
  const cookieHeader = extractHeaderValue(content, "cookie");
  if (cookieHeader) {
    return cookieHeader;
  }

  return stripUtf8Bom(content).trim();
}

function parseCookieHeader(content: string): CookiePair[] {
  const cookieHeader = extractCookieHeader(content);
  const pairs: CookiePair[] = [];

  for (const part of cookieHeader.split(";")) {
    const trimmed = part.trim();
    if (!trimmed || trimmed.toLowerCase().startsWith("cookie:")) {
      continue;
    }

    const separatorIndex = trimmed.indexOf("=");
    if (separatorIndex <= 0) {
      continue;
    }

    const name = trimmed.slice(0, separatorIndex).trim();
    const value = trimmed.slice(separatorIndex + 1).trim();
    if (!name || name.startsWith("$") || /[\r\n\t]/.test(name + value)) {
      continue;
    }

    pairs.push({ name, value });
  }

  return pairs;
}

function inferCookieDomain(content: string, pairs: CookiePair[]): string | null {
  const hostDomain = extractHost(content);
  if (hostDomain) {
    const normalized = normalizeDomainFromHost(hostDomain);
    if (normalized) {
      return normalized;
    }
  }

  if (pairs.some((pair) => BILIBILI_COOKIE_NAMES.has(pair.name))) {
    return ".bilibili.com";
  }

  if (
    pairs.some(
      (pair) =>
        YOUTUBE_COOKIE_NAMES.has(pair.name) ||
        pair.name.startsWith("__Secure-") ||
        pair.name.startsWith("ST-")
    )
  ) {
    return ".youtube.com";
  }

  return null;
}

function cookiePairsToNetscape(content: string, pairs: CookiePair[]): string {
  const domain = inferCookieDomain(content, pairs);
  if (!domain) {
    throw new UnsupportedCookieFormatError();
  }

  const lines = pairs.map(({ name, value }) => {
    const secure = name.startsWith("__Secure-") || name.startsWith("__Host-");
    return [domain, "TRUE", "/", secure ? "TRUE" : "FALSE", "0", name, value].join(
      "\t"
    );
  });

  return `${NETSCAPE_HEADER}\n${GENERATED_COMMENT}\n${lines.join("\n")}\n`;
}

export function normalizeCookiesFileContent(content: string): string {
  const text = stripUtf8Bom(content).replace(/\0/g, "").trim();
  if (!text) {
    throw new UnsupportedCookieFormatError();
  }

  if (isValidNetscapeCookiesFile(text)) {
    return `${text}\n`;
  }

  const pairs = parseCookieHeader(text);
  if (pairs.length === 0) {
    throw new UnsupportedCookieFormatError();
  }

  return cookiePairsToNetscape(text, pairs);
}
