import path from "path";
import downloadManager from "../../services/downloadManager";
import { Settings } from "../../types/settings";
import { logger } from "../../utils/logger";
import { resolveSafeChildPath, writeFileSafe } from "../../utils/security";

const hasOwnSetting = (
  settings: Partial<Settings>,
  key: keyof Settings
): boolean => Object.prototype.hasOwnProperty.call(settings, key);

export const moveSubtitlesIfSettingChanged = async (
  existingSettings: Settings,
  settingsToPersist: Partial<Settings>
): Promise<void> => {
  if (
    !hasOwnSetting(settingsToPersist, "moveSubtitlesToVideoFolder") ||
    settingsToPersist.moveSubtitlesToVideoFolder ===
      existingSettings.moveSubtitlesToVideoFolder ||
    settingsToPersist.moveSubtitlesToVideoFolder === undefined
  ) {
    return;
  }

  const { moveAllSubtitles } = await import("../../services/subtitleService");
  moveAllSubtitles(settingsToPersist.moveSubtitlesToVideoFolder).catch((err) =>
    logger.error("Error moving subtitles in background:", err)
  );
};

export const moveThumbnailsIfSettingChanged = async (
  existingSettings: Settings,
  settingsToPersist: Partial<Settings>
): Promise<void> => {
  if (
    !hasOwnSetting(settingsToPersist, "moveThumbnailsToVideoFolder") ||
    settingsToPersist.moveThumbnailsToVideoFolder ===
      existingSettings.moveThumbnailsToVideoFolder ||
    settingsToPersist.moveThumbnailsToVideoFolder === undefined
  ) {
    return;
  }

  const { moveAllThumbnails } = await import("../../services/thumbnailService");
  moveAllThumbnails(settingsToPersist.moveThumbnailsToVideoFolder).catch(
    (err) => logger.error("Error moving thumbnails in background:", err)
  );
};

export const persistAllowedHostsEnv = async (
  existingSettings: Settings,
  settingsToPersist: Partial<Settings>,
  finalSettings: Settings
): Promise<void> => {
  const allowedHostsChanged =
    hasOwnSetting(settingsToPersist, "allowedHosts") &&
    settingsToPersist.allowedHosts !== existingSettings.allowedHosts;

  if (!allowedHostsChanged) {
    return;
  }

  try {
    // __dirname is backend/src/controllers/settingsController; resolve to the
    // frontend root (was "../../../frontend" when this lived in the controller).
    const basePath = path.resolve(__dirname, "../../../../frontend");
    const envLocalPath = resolveSafeChildPath(basePath, ".env.local");

    const sanitizedHosts = (finalSettings.allowedHosts || "")
      .replace(/[\r\n]/g, "")
      .replace(/[^\w\s.,-]/g, "");

    const envContent = `# Auto-generated by MyTube settings\n# Restart dev server for changes to take effect\nVITE_ALLOWED_HOSTS=${sanitizedHosts}\n`;
    // Async write to keep the FS I/O off the event loop on this request path.
    await writeFileSafe(envLocalPath, basePath, envContent, "utf8");
    logger.info(`Updated VITE_ALLOWED_HOSTS in .env.local: ${sanitizedHosts}`);
  } catch (error) {
    logger.warn(
      "Failed to write allowedHosts to .env.local:",
      error instanceof Error ? error : new Error(String(error))
    );
  }
};

export const applyRuntimeSettingChanges = (
  settingsToPersist: Partial<Settings>,
  finalSettings: Settings
): void => {
  if (
    hasOwnSetting(settingsToPersist, "maxConcurrentDownloads") &&
    finalSettings.maxConcurrentDownloads !== undefined
  ) {
    downloadManager.setMaxConcurrentDownloads(
      finalSettings.maxConcurrentDownloads
    );
  }
};
