import { describe, expect, it } from "vitest";
import {
  buildEpisodeNfo,
  buildEpisodeOccurrenceId,
  buildSeasonNfo,
  buildSeasonUniqueId,
  buildShowNfo,
  buildShowUniqueId,
  normalizeShowIdentifier,
  normalizeVideoDateToDay,
} from "../../../services/mediaServerExport/nfoBuilders";
import type { Video } from "../../../services/storageService";

function createVideo(overrides: Partial<Video> = {}): Video {
  return {
    id: "video-1",
    title: "How Many Ants Live On Earth?",
    author: "Kurzgesagt",
    description: "Sample description from MyTube.",
    date: "20260525",
    addedAt: "2026-05-25T14:32:11.000Z",
    createdAt: "2026-05-25T14:32:11.000Z",
    duration: "541",
    tags: ["science", "youtube"],
    sourceUrl: "https://www.youtube.com/watch?v=ants",
    ...overrides,
  } as unknown as Video;
}

/**
 * Regression boundary for issue #411. The playlist_tv layout adds a season
 * builder and occurrence-scoped episode ids; the adjacent output frozen here
 * must stay byte-identical.
 */
describe("mediaServerExport nfoBuilders (adjacent regression boundary)", () => {
  it("builds the adjacent episode NFO exactly", () => {
    const nfo = buildEpisodeNfo({
      video: createVideo(),
      showTitle: "Kurzgesagt",
      seasonNumber: 2026,
      episodeNumber: 52501,
      thumbFilename: "s2026e052501 - How Many Ants Live On Earth-thumb.jpg",
    });

    expect(nfo).toBe(
      [
        "<!-- Generated by MyTube. Manual edits may be overwritten. -->",
        "<episodedetails>",
        "  <title>How Many Ants Live On Earth?</title>",
        "  <showtitle>Kurzgesagt</showtitle>",
        "  <plot>Sample description from MyTube.</plot>",
        "  <season>2026</season>",
        "  <episode>52501</episode>",
        "  <aired>2026-05-25</aired>",
        "  <premiered>2026-05-25</premiered>",
        "  <dateadded>2026-05-25T14:32:11.000Z</dateadded>",
        "  <runtime>10</runtime>",
        "  <studio>Kurzgesagt</studio>",
        "  <tag>science</tag>",
        "  <tag>youtube</tag>",
        "  <id>mytube:video:video-1</id>",
        '  <uniqueid type="mytube" default="true">mytube:video:video-1</uniqueid>',
        "  <thumb>s2026e052501 - How Many Ants Live On Earth-thumb.jpg</thumb>",
        "</episodedetails>",
        "",
      ].join("\n")
    );
  });

  it("keeps the adjacent episode unique id keyed only by video id", () => {
    const nfo = buildEpisodeNfo({
      video: createVideo({ id: "abc-123" }),
      showTitle: "Kurzgesagt",
    });

    expect(nfo).toContain("<id>mytube:video:abc-123</id>");
    expect(nfo).toContain(
      '<uniqueid type="mytube" default="true">mytube:video:abc-123</uniqueid>'
    );
    expect(nfo).not.toContain("<season>");
    expect(nfo).not.toContain("<episode>");
  });

  it("builds the adjacent show NFO exactly", () => {
    const nfo = buildShowNfo({
      showTitle: "Kurzgesagt",
      plot: "",
      premiered: "2026-01-03",
      studio: "Kurzgesagt",
    });

    expect(nfo).toBe(
      [
        "<!-- Generated by MyTube. Manual edits may be overwritten. -->",
        "<tvshow>",
        "  <title>Kurzgesagt</title>",
        "  <sorttitle>Kurzgesagt</sorttitle>",
        "  <plot></plot>",
        "  <premiered>2026-01-03</premiered>",
        "  <studio>Kurzgesagt</studio>",
        "  <id>mytube:show:kurzgesagt</id>",
        '  <uniqueid type="mytube" default="true">mytube:show:kurzgesagt</uniqueid>',
        "</tvshow>",
        "",
      ].join("\n")
    );
  });

  it("escapes XML metacharacters at every level", () => {
    const episode = buildEpisodeNfo({
      video: createVideo({
        title: `Tom & Jerry <"best"> 'ever'`,
        description: "a & b < c > d",
        tags: ["a&b"],
      }),
      showTitle: `Show & Co <x>`,
    });

    expect(episode).toContain(
      "<title>Tom &amp; Jerry &lt;&quot;best&quot;&gt; &apos;ever&apos;</title>"
    );
    expect(episode).toContain("<showtitle>Show &amp; Co &lt;x&gt;</showtitle>");
    expect(episode).toContain("<plot>a &amp; b &lt; c &gt; d</plot>");
    expect(episode).toContain("<tag>a&amp;b</tag>");

    const show = buildShowNfo({ showTitle: `Show & Co <x>`, plot: `p & q` });
    expect(show).toContain("<title>Show &amp; Co &lt;x&gt;</title>");
    expect(show).toContain("<plot>p &amp; q</plot>");
  });

  it("normalizes dates and runtimes deterministically", () => {
    expect(normalizeVideoDateToDay("20260525")).toBe("2026-05-25");
    expect(normalizeVideoDateToDay("2026-05-25")).toBe("2026-05-25");
    expect(normalizeVideoDateToDay("not-a-date")).toBeUndefined();
    expect(normalizeVideoDateToDay(undefined)).toBeUndefined();

    expect(
      buildEpisodeNfo({ video: createVideo({ duration: "30" }), showTitle: "S" })
    ).toContain("<runtime>1</runtime>");
    expect(
      buildEpisodeNfo({ video: createVideo({ duration: "0" }), showTitle: "S" })
    ).not.toContain("<runtime>");
  });

  it("normalizes show identifiers to a stable slug", () => {
    expect(normalizeShowIdentifier("Kurzgesagt – In a Nutshell")).toBe(
      "kurzgesagt-in-a-nutshell"
    );
    expect(normalizeShowIdentifier("  ...  ")).toBe("show");
  });

  it("always ends with a single trailing newline", () => {
    expect(
      buildEpisodeNfo({ video: createVideo(), showTitle: "S" }).endsWith(
        "</episodedetails>\n"
      )
    ).toBe(true);
    expect(
      buildShowNfo({ showTitle: "S", plot: "" }).endsWith("</tvshow>\n")
    ).toBe(true);
  });
});

/**
 * Issue #411 additions. These only apply to the playlist_tv layout; the
 * adjacent output frozen above must be unaffected.
 */
describe("mediaServerExport nfoBuilders (playlist_tv layout)", () => {
  it("builds season.nfo with a <season> root and a <seasonnumber> child", () => {
    const nfo = buildSeasonNfo({
      seasonNumber: 3,
      title: "Space Time",
      plot: "Everything about spacetime.",
      seasonUniqueId: "mytube:season:collection-1",
    });

    expect(nfo).toBe(
      [
        "<!-- Generated by MyTube. Manual edits may be overwritten. -->",
        "<season>",
        "  <title>Space Time</title>",
        "  <sorttitle>Space Time</sorttitle>",
        "  <seasonnumber>3</seasonnumber>",
        "  <plot>Everything about spacetime.</plot>",
        "  <id>mytube:season:collection-1</id>",
        '  <uniqueid type="mytube" default="true">mytube:season:collection-1</uniqueid>',
        "</season>",
        "",
      ].join("\n")
    );

    // The season number must never be carried in an <episode> tag, and the root
    // must not be <episodedetails>.
    expect(nfo).not.toContain("<episode>");
    expect(nfo).not.toContain("episodedetails");
  });

  it("builds the Season 00 specials NFO", () => {
    const nfo = buildSeasonNfo({
      seasonNumber: 0,
      title: "Specials / Unassigned",
      plot: "",
      seasonUniqueId: "mytube:season:mss_abc:0",
    });

    expect(nfo).toContain("<title>Specials / Unassigned</title>");
    expect(nfo).toContain("<seasonnumber>0</seasonnumber>");
    expect(nfo).toContain("<plot></plot>");
    expect(nfo).toContain("<id>mytube:season:mss_abc:0</id>");
  });

  it("escapes XML metacharacters in season fields", () => {
    const nfo = buildSeasonNfo({
      seasonNumber: 1,
      title: `Q&A <"best"> 'ever'`,
      plot: "a & b < c",
      seasonUniqueId: "mytube:season:c&1",
    });

    expect(nfo).toContain(
      "<title>Q&amp;A &lt;&quot;best&quot;&gt; &apos;ever&apos;</title>"
    );
    expect(nfo).toContain("<plot>a &amp; b &lt; c</plot>");
    expect(nfo).toContain("<id>mytube:season:c&amp;1</id>");
    expect(nfo).toContain(
      '<uniqueid type="mytube" default="true">mytube:season:c&amp;1</uniqueid>'
    );
  });

  it("derives season ids from the collection, or from the show for Season 00", () => {
    expect(
      buildSeasonUniqueId({ collectionId: "c1", showId: "s1", seasonNumber: 2 })
    ).toBe("mytube:season:c1");
    expect(buildSeasonUniqueId({ showId: "s1", seasonNumber: 0 })).toBe(
      "mytube:season:s1:0"
    );
  });

  it("gives the same video two distinct occurrence ids in two seasons", () => {
    const first = buildEpisodeOccurrenceId({
      showId: "mss_abc",
      seasonNumber: 1,
      episodeNumber: 5,
      videoId: "video-1",
    });
    const second = buildEpisodeOccurrenceId({
      showId: "mss_abc",
      seasonNumber: 2,
      episodeNumber: 5,
      videoId: "video-1",
    });

    expect(first).toBe("mytube:episode:mss_abc:1:5:video-1");
    expect(first).not.toBe(second);

    const firstNfo = buildEpisodeNfo({
      video: createVideo(),
      showTitle: "Kurzgesagt",
      seasonNumber: 1,
      episodeNumber: 5,
      occurrenceId: first,
    });
    const secondNfo = buildEpisodeNfo({
      video: createVideo(),
      showTitle: "Kurzgesagt",
      seasonNumber: 2,
      episodeNumber: 5,
      occurrenceId: second,
    });

    expect(firstNfo).toContain(
      '<uniqueid type="mytube" default="true">mytube:episode:mss_abc:1:5:video-1</uniqueid>'
    );
    expect(secondNfo).toContain(
      '<uniqueid type="mytube" default="true">mytube:episode:mss_abc:2:5:video-1</uniqueid>'
    );
    // The per-video id is deliberately NOT emitted alongside the occurrence id;
    // a media server would otherwise still collapse the two occurrences.
    expect(firstNfo).not.toContain("mytube:video:video-1");
  });

  describe("TMDB unique id", () => {
    it("emits a second uniqueid for a confirmed TV match", () => {
      const nfo = buildShowNfo({
        showTitle: "人民的名义",
        plot: "",
        showUniqueId: "mytube:show:collection:c1",
        tmdbId: 72517,
        tmdbMediaType: "tv",
      });

      expect(nfo).toContain(
        '<uniqueid type="mytube" default="true">mytube:show:collection:c1</uniqueid>'
      );
      expect(nfo).toContain('<uniqueid type="tmdb">72517</uniqueid>');
      // The MyTube id stays the default one.
      expect(nfo).not.toContain('<uniqueid type="tmdb" default');
    });

    /**
     * TMDB movie and TV ids share a numeric space, and an id in `tvshow.nfo` is
     * read as a TV id — emitting a movie id would point the server at an
     * unrelated series.
     */
    it("omits the id for a confirmed movie match", () => {
      const nfo = buildShowNfo({
        showTitle: "A Film",
        plot: "Overview retained.",
        showUniqueId: "mytube:show:collection:c1",
        tmdbId: 603,
        tmdbMediaType: "movie",
      });

      expect(nfo).not.toContain('type="tmdb"');
      // The rest of the movie's metadata is still used.
      expect(nfo).toContain("<plot>Overview retained.</plot>");
    });

    it("omits the id for absent or unusable values", () => {
      for (const input of [
        {},
        { tmdbId: 0, tmdbMediaType: "tv" as const },
        { tmdbId: -5, tmdbMediaType: "tv" as const },
        { tmdbId: 1.5, tmdbMediaType: "tv" as const },
        { tmdbId: 72517 },
      ]) {
        const nfo = buildShowNfo({
          showTitle: "Show",
          plot: "",
          showUniqueId: "mytube:show:collection:c1",
          ...input,
        });
        expect(nfo).not.toContain('type="tmdb"');
      }
    });
  });

  it("uses a stable identity-derived show id when one is supplied", () => {
    const nfo = buildShowNfo({
      showTitle: "Kurzgesagt – In a Nutshell",
      plot: "Optimistic nihilism.",
      showUniqueId: buildShowUniqueId("youtube:channel-id:UC123"),
    });

    expect(nfo).toContain("<id>mytube:show:youtube:channel-id:UC123</id>");
    expect(nfo).toContain("<plot>Optimistic nihilism.</plot>");
    // A channel rename must not change the id.
    expect(
      buildShowNfo({
        showTitle: "Completely New Name",
        plot: "",
        showUniqueId: buildShowUniqueId("youtube:channel-id:UC123"),
      })
    ).toContain("<id>mytube:show:youtube:channel-id:UC123</id>");
  });
});
