import { describe, expect, it } from "vitest";
import {
  buildEpisodeNfo,
  buildEpisodeOccurrenceId,
  buildSeasonNfo,
  buildSeasonUniqueId,
  buildShowNfo,
  buildShowUniqueId,
} from "../../../services/mediaServerExport/nfoBuilders";
import type { Video } from "../../../services/storageService";

function createVideo(overrides: Partial<Video> = {}): Video {
  return {
    id: "video-1",
    title: "Human Origins",
    author: "Kurzgesagt",
    date: "20260115",
    duration: "610",
    description: "A & B <c>",
    sourceUrl: "https://example.com/v",
    createdAt: "2026-01-15T00:00:00.000Z",
    addedAt: "2026-01-15",
    tags: ["science"],
    ...overrides,
  } as unknown as Video;
}

describe("mediaServerExport/nfoBuilders", () => {
  it("keeps the adjacent episode NFO byte-identical", () => {
    expect(
      buildEpisodeNfo({
        video: createVideo(),
        showTitle: "Kurzgesagt",
        seasonNumber: 1,
        episodeNumber: 2,
        thumbFilename: "Human Origins-thumb.jpg",
      })
    ).toBe(
      [
        "<!-- Generated by MyTube. Manual edits may be overwritten. -->",
        "<episodedetails>",
        "  <title>Human Origins</title>",
        "  <showtitle>Kurzgesagt</showtitle>",
        "  <plot>A &amp; B &lt;c&gt;</plot>",
        "  <season>1</season>",
        "  <episode>2</episode>",
        "  <aired>2026-01-15</aired>",
        "  <premiered>2026-01-15</premiered>",
        "  <dateadded>2026-01-15</dateadded>",
        "  <runtime>11</runtime>",
        "  <studio>Kurzgesagt</studio>",
        "  <tag>science</tag>",
        "  <id>mytube:video:video-1</id>",
        '  <uniqueid type="mytube" default="true">mytube:video:video-1</uniqueid>',
        "  <thumb>Human Origins-thumb.jpg</thumb>",
        "</episodedetails>",
        "",
      ].join("\n")
    );
  });

  it("uses the supplied occurrence id so duplicate memberships stay distinct", () => {
    const first = buildEpisodeNfo({
      video: createVideo(),
      showTitle: "Kurzgesagt",
      seasonNumber: 1,
      episodeNumber: 2,
      uniqueId: buildEpisodeOccurrenceId("show-1", 1, 2, "video-1"),
    });
    const second = buildEpisodeNfo({
      video: createVideo(),
      showTitle: "Kurzgesagt",
      seasonNumber: 2,
      episodeNumber: 5,
      uniqueId: buildEpisodeOccurrenceId("show-1", 2, 5, "video-1"),
    });

    expect(first).toContain("mytube:episode:show-1:1:2:video-1");
    expect(second).toContain("mytube:episode:show-1:2:5:video-1");
    expect(first).not.toContain("mytube:video:video-1");
  });

  it("builds a season NFO with a season root and escaped values", () => {
    expect(
      buildSeasonNfo({
        title: 'Space & "Time"',
        plot: "Playlist <plot>",
        seasonNumber: 3,
        uniqueId: buildSeasonUniqueId("show-1", 3),
      })
    ).toBe(
      [
        "<!-- Generated by MyTube. Manual edits may be overwritten. -->",
        "<season>",
        "  <title>Space &amp; &quot;Time&quot;</title>",
        "  <sorttitle>Space &amp; &quot;Time&quot;</sorttitle>",
        "  <seasonnumber>3</seasonnumber>",
        "  <plot>Playlist &lt;plot&gt;</plot>",
        "  <id>mytube:season:show-1:3</id>",
        '  <uniqueid type="mytube" default="true">mytube:season:show-1:3</uniqueid>',
        "</season>",
        "",
      ].join("\n")
    );
  });

  it("emits Season 00 with an empty plot", () => {
    const nfo = buildSeasonNfo({
      title: "Specials / Unassigned",
      plot: "",
      seasonNumber: 0,
      uniqueId: buildSeasonUniqueId("show-1", 0),
    });
    expect(nfo).toContain("<seasonnumber>0</seasonnumber>");
    expect(nfo).toContain("<plot></plot>");
  });

  it("keeps the adjacent show id derivation and honours an explicit one", () => {
    expect(buildShowNfo({ showTitle: "Kurzgesagt", plot: "" })).toContain(
      "<id>mytube:show:kurzgesagt</id>"
    );
    expect(
      buildShowNfo({
        showTitle: "Kurzgesagt",
        plot: "Channel description",
        uniqueId: buildShowUniqueId("show-1"),
      })
    ).toContain("<id>mytube:show:show-1</id>");
  });

  it("never borrows an episode description for the show plot", () => {
    const nfo = buildShowNfo({ showTitle: "Kurzgesagt", plot: "" });
    expect(nfo).toContain("<plot></plot>");
  });
});
