import fs from "fs-extra";
import os from "os";
import path from "path";
import { afterAll, beforeEach, describe, expect, it, vi } from "vitest";
import type { Video } from "../../../services/storageService";

const testPaths = vi.hoisted(() => {
  const fs = require("fs-extra") as typeof import("fs-extra");
  const os = require("os") as typeof import("os");
  const path = require("path") as typeof import("path");
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "mytube-orphan-sweep-"));

  return {
    root,
    videos: path.join(root, "videos"),
    images: path.join(root, "images"),
    imagesSmall: path.join(root, "images-small"),
    avatars: path.join(root, "avatars"),
    subtitles: path.join(root, "subtitles"),
  };
});

vi.mock("../../../config/paths", () => ({
  AVATARS_DIR: testPaths.avatars,
  IMAGES_DIR: testPaths.images,
  IMAGES_SMALL_DIR: testPaths.imagesSmall,
  VIDEOS_DIR: testPaths.videos,
  SUBTITLES_DIR: testPaths.subtitles,
}));

vi.mock("../../../utils/logger", () => ({
  logger: {
    error: vi.fn(),
    warn: vi.fn(),
    info: vi.fn(),
  },
}));

import { sweepOrphanMediaServerArtifacts } from "../../../services/mediaServerExport/orphanSweep";

function writeFile(targetPath: string, contents: string): void {
  fs.ensureDirSync(path.dirname(targetPath));
  fs.writeFileSync(targetPath, contents, "utf8");
}

function fileExists(relativePath: string): boolean {
  return fs.existsSync(path.join(testPaths.videos, relativePath));
}

function createVideo(): Video {
  return {
    id: "video-1",
    title: "Current Episode",
    videoPath: "/videos/Show/Season 01/current.mp4",
    videoFilename: "current.mp4",
    sourceUrl: "https://example.com/current",
    createdAt: "2026-06-01T00:00:00.000Z",
  } as unknown as Video;
}

describe("mediaServerExport orphanSweep", () => {
  beforeEach(() => {
    fs.emptyDirSync(testPaths.root);
    fs.ensureDirSync(testPaths.videos);
    fs.ensureDirSync(testPaths.images);
    fs.ensureDirSync(testPaths.imagesSmall);
    fs.ensureDirSync(testPaths.avatars);
    fs.ensureDirSync(testPaths.subtitles);
  });

  afterAll(() => {
    fs.removeSync(testPaths.root);
  });

  it("deletes only provably MyTube-generated orphan artifacts", () => {
    writeFile(path.join(testPaths.videos, "Show/Season 01/current.mp4"), "video");
    writeFile(
      path.join(testPaths.videos, "Show/Season 01/current.nfo"),
      "<!-- Generated by MyTube. -->"
    );
    writeFile(path.join(testPaths.videos, "Show/Season 01/current-thumb.jpg"), "jpg");
    writeFile(
      path.join(testPaths.videos, "Show/Season 01/current.info.json"),
      JSON.stringify({ _mytube: { generatedBy: "mytube" } })
    );
    writeFile(path.join(testPaths.videos, "Show/tvshow.nfo"), "<uniqueid type=\"mytube\">Show</uniqueid>");
    writeFile(path.join(testPaths.videos, "Show/show.jpg"), "show");

    writeFile(
      path.join(testPaths.videos, "Old/Season 01/stale.nfo"),
      "<!-- Generated by MyTube. -->"
    );
    writeFile(path.join(testPaths.videos, "Old/Season 01/stale-thumb.jpg"), "jpg");
    writeFile(
      path.join(testPaths.videos, "Old/Season 01/stale.info.json"),
      JSON.stringify({ _mytube: { generatedBy: "mytube" } })
    );
    writeFile(
      path.join(testPaths.videos, "Old/Season 01/user.nfo"),
      "<episodedetails><title>User file</title></episodedetails>"
    );
    writeFile(path.join(testPaths.videos, "Old/Season 01/user-thumb.jpg"), "jpg");
    writeFile(path.join(testPaths.videos, "Old/tvshow.nfo"), "<uniqueid type=\"mytube\">Old</uniqueid>");
    writeFile(path.join(testPaths.videos, "Old/show.jpg"), "show");
    writeFile(path.join(testPaths.videos, "Old/poster.jpg"), "poster");
    writeFile(path.join(testPaths.videos, "Old/folder.jpg"), "folder");

    const result = sweepOrphanMediaServerArtifacts([createVideo()]);

    expect(result.sweptFiles).toBe(7);
    expect(result.sweptList).toEqual([
      "Old/Season 01/stale-thumb.jpg",
      "Old/Season 01/stale.info.json",
      "Old/Season 01/stale.nfo",
      "Old/folder.jpg",
      "Old/poster.jpg",
      "Old/show.jpg",
      "Old/tvshow.nfo",
    ]);

    expect(fileExists("Show/Season 01/current.nfo")).toBe(true);
    expect(fileExists("Show/Season 01/current-thumb.jpg")).toBe(true);
    expect(fileExists("Show/Season 01/current.info.json")).toBe(true);
    expect(fileExists("Show/tvshow.nfo")).toBe(true);
    expect(fileExists("Show/show.jpg")).toBe(true);

    expect(fileExists("Old/Season 01/stale.nfo")).toBe(false);
    expect(fileExists("Old/Season 01/stale-thumb.jpg")).toBe(false);
    expect(fileExists("Old/Season 01/stale.info.json")).toBe(false);
    expect(fileExists("Old/tvshow.nfo")).toBe(false);
    expect(fileExists("Old/show.jpg")).toBe(false);
    expect(fileExists("Old/poster.jpg")).toBe(false);
    expect(fileExists("Old/folder.jpg")).toBe(false);

    expect(fileExists("Old/Season 01/user.nfo")).toBe(true);
    expect(fileExists("Old/Season 01/user-thumb.jpg")).toBe(true);
  });
});
