import fs from "fs-extra";
import os from "os";
import path from "path";
import { afterAll, beforeEach, describe, expect, it, vi } from "vitest";
import type { Video } from "../../../services/storageService";

const testPaths = vi.hoisted(() => {
  const fs = require("fs-extra") as typeof import("fs-extra");
  const os = require("os") as typeof import("os");
  const path = require("path") as typeof import("path");
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "mytube-media-export-"));

  return {
    root,
    videos: path.join(root, "videos"),
    images: path.join(root, "images"),
    imagesSmall: path.join(root, "images-small"),
    avatars: path.join(root, "avatars"),
    subtitles: path.join(root, "subtitles"),
  };
});

const getSettingsMock = vi.hoisted(() => vi.fn());

vi.mock("../../../config/paths", () => ({
  AVATARS_DIR: testPaths.avatars,
  IMAGES_DIR: testPaths.images,
  IMAGES_SMALL_DIR: testPaths.imagesSmall,
  VIDEOS_DIR: testPaths.videos,
  SUBTITLES_DIR: testPaths.subtitles,
}));

vi.mock("../../../services/storageService/settings", () => ({
  getSettings: getSettingsMock,
}));

vi.mock("../../../utils/logger", () => ({
  logger: {
    error: vi.fn(),
    warn: vi.fn(),
    info: vi.fn(),
  },
}));

import {
  removeMediaServerArtifactsForVideo,
  syncMediaServerShowArtifactsForShowRoot,
  syncMediaServerArtifactsForRecord,
} from "../../../services/mediaServerExport";

function writeFile(targetPath: string, contents: string): void {
  fs.ensureDirSync(path.dirname(targetPath));
  fs.writeFileSync(targetPath, contents, "utf8");
}

function createVideoRecord(overrides: Partial<Video> = {}): Video {
  return {
    id: "video-1",
    title: "How Many Ants Live On Earth?",
    author: "Kurzgesagt",
    description: "Sample description from MyTube.",
    date: "20260525",
    source: "youtube",
    sourceUrl: "https://www.youtube.com/watch?v=ants",
    videoFilename: "s2026e052501 - How Many Ants Live On Earth.mp4",
    videoPath:
      "/videos/Kurzgesagt/Season 2026/s2026e052501 - How Many Ants Live On Earth.mp4",
    thumbnailPath: "/images/Kurzgesagt/episode.jpg",
    thumbnailUrl: "/images/Kurzgesagt/episode.jpg",
    authorAvatarPath: "/avatars/Kurzgesagt/avatar.jpg",
    authorAvatarFilename: "avatar.jpg",
    addedAt: "2026-05-25T14:32:11.000Z",
    createdAt: "2026-05-25T14:32:11.000Z",
    duration: "541",
    tags: ["science", "youtube"],
    channelUrl: "https://www.youtube.com/@kurzgesagt",
    ...overrides,
  };
}

describe("mediaServerExport syncService", () => {
  beforeEach(() => {
    fs.emptyDirSync(testPaths.root);
    fs.ensureDirSync(testPaths.videos);
    fs.ensureDirSync(testPaths.images);
    fs.ensureDirSync(testPaths.imagesSmall);
    fs.ensureDirSync(testPaths.avatars);
    fs.ensureDirSync(testPaths.subtitles);
    getSettingsMock.mockReset();
  });

  afterAll(() => {
    fs.removeSync(testPaths.root);
  });

  it("writes episode, show, artwork, and source-json sidecars", () => {
    getSettingsMock.mockReturnValue({
      mediaServerExportMode: "nfo_and_source_json",
    });

    const video = createVideoRecord();
    const olderShowVideo = createVideoRecord({
      id: "video-0",
      date: "20260103",
      videoPath: "/videos/Kurzgesagt/Season 2026/s2026e010301 - Older Episode.mp4",
      videoFilename: "s2026e010301 - Older Episode.mp4",
      thumbnailPath: null,
      thumbnailUrl: undefined,
      authorAvatarPath: undefined,
      authorAvatarFilename: undefined,
    });

    writeFile(
      path.join(
        testPaths.videos,
        "Kurzgesagt/Season 2026/s2026e052501 - How Many Ants Live On Earth.mp4"
      ),
      "video"
    );
    writeFile(path.join(testPaths.images, "Kurzgesagt/episode.jpg"), "episode-image");
    writeFile(path.join(testPaths.avatars, "Kurzgesagt/avatar.jpg"), "show-avatar");

    syncMediaServerArtifactsForRecord(video, {
      rawSourceInfo: {
        id: "ants-raw",
        title: "Raw yt-dlp title",
        uploader: "Kurzgesagt",
      },
      libraryVideos: [olderShowVideo, video],
    });

    const episodeNfo = fs.readFileSync(
      path.join(
        testPaths.videos,
        "Kurzgesagt/Season 2026/s2026e052501 - How Many Ants Live On Earth.nfo"
      ),
      "utf8"
    );
    const sourceJson = JSON.parse(
      fs.readFileSync(
        path.join(
          testPaths.videos,
          "Kurzgesagt/Season 2026/s2026e052501 - How Many Ants Live On Earth.info.json"
        ),
        "utf8"
      )
    );
    const showNfo = fs.readFileSync(
      path.join(testPaths.videos, "Kurzgesagt/tvshow.nfo"),
      "utf8"
    );

    expect(episodeNfo).toContain("Generated by MyTube");
    expect(episodeNfo).toContain("<showtitle>Kurzgesagt</showtitle>");
    expect(episodeNfo).toContain("<season>2026</season>");
    expect(episodeNfo).toContain("<episode>52501</episode>");
    expect(episodeNfo).toContain(
      "<thumb>s2026e052501 - How Many Ants Live On Earth-thumb.jpg</thumb>"
    );
    expect(sourceJson.id).toBe("ants-raw");
    expect(sourceJson.description).toBe("Sample description from MyTube.");
    expect(sourceJson.webpage_url).toBe("https://www.youtube.com/watch?v=ants");
    expect(sourceJson.channel_url).toBe("https://www.youtube.com/@kurzgesagt");
    expect(sourceJson.tags).toEqual(["science", "youtube"]);
    expect(sourceJson._mytube.rawSourcePreserved).toBe(true);
    expect(showNfo).toContain("<premiered>2026-01-03</premiered>");
    expect(
      fs.readFileSync(path.join(testPaths.videos, "Kurzgesagt/show.jpg"), "utf8")
    ).toBe("show-avatar");
    expect(
      fs.readFileSync(path.join(testPaths.videos, "Kurzgesagt/poster.jpg"), "utf8")
    ).toBe("show-avatar");
    expect(
      fs.readFileSync(
        path.join(
          testPaths.videos,
          "Kurzgesagt/Season 2026/s2026e052501 - How Many Ants Live On Earth-thumb.jpg"
        ),
        "utf8"
      )
    ).toBe("episode-image");
  });

  it("skips source-json in nfo mode and removes generated artifacts on delete", () => {
    getSettingsMock.mockReturnValue({
      mediaServerExportMode: "nfo",
    });

    const video = createVideoRecord();
    writeFile(
      path.join(
        testPaths.videos,
        "Kurzgesagt/Season 2026/s2026e052501 - How Many Ants Live On Earth.mp4"
      ),
      "video"
    );
    writeFile(path.join(testPaths.images, "Kurzgesagt/episode.jpg"), "episode-image");
    writeFile(path.join(testPaths.avatars, "Kurzgesagt/avatar.jpg"), "show-avatar");

    syncMediaServerArtifactsForRecord(video, {
      libraryVideos: [video],
    });

    expect(
      fs.existsSync(
        path.join(
          testPaths.videos,
          "Kurzgesagt/Season 2026/s2026e052501 - How Many Ants Live On Earth.info.json"
        )
      )
    ).toBe(false);

    removeMediaServerArtifactsForVideo(video, {
      libraryVideos: [],
    });

    expect(
      fs.existsSync(
        path.join(
          testPaths.videos,
          "Kurzgesagt/Season 2026/s2026e052501 - How Many Ants Live On Earth.nfo"
        )
      )
    ).toBe(false);
    expect(fs.existsSync(path.join(testPaths.videos, "Kurzgesagt/tvshow.nfo"))).toBe(
      false
    );
    expect(fs.existsSync(path.join(testPaths.videos, "Kurzgesagt/show.jpg"))).toBe(
      false
    );
  });

  it("does not write source or show sidecars when the video file is missing", () => {
    getSettingsMock.mockReturnValue({
      mediaServerExportMode: "nfo_and_source_json",
    });

    const video = createVideoRecord();
    writeFile(path.join(testPaths.images, "Kurzgesagt/episode.jpg"), "episode-image");

    syncMediaServerArtifactsForRecord(video, {
      rawSourceInfo: { id: "raw" },
      libraryVideos: [video],
    });

    expect(
      fs.existsSync(
        path.join(
          testPaths.videos,
          "Kurzgesagt/Season 2026/s2026e052501 - How Many Ants Live On Earth.nfo"
        )
      )
    ).toBe(false);
    expect(
      fs.existsSync(
        path.join(
          testPaths.videos,
          "Kurzgesagt/Season 2026/s2026e052501 - How Many Ants Live On Earth.info.json"
        )
      )
    ).toBe(false);
    expect(fs.existsSync(path.join(testPaths.videos, "Kurzgesagt/tvshow.nfo"))).toBe(
      false
    );
  });

  it("rebuilds a show root from remaining library videos after a move", () => {
    getSettingsMock.mockReturnValue({
      mediaServerExportMode: "nfo",
    });

    const remainingVideo = createVideoRecord({
      id: "video-2",
      title: "Remaining Episode",
      date: "20260601",
      videoPath: "/videos/Kurzgesagt/Season 2026/s2026e060101 - Remaining Episode.mp4",
      videoFilename: "s2026e060101 - Remaining Episode.mp4",
      thumbnailPath: null,
      thumbnailUrl: undefined,
      authorAvatarPath: undefined,
      authorAvatarFilename: undefined,
    });

    writeFile(
      path.join(
        testPaths.videos,
        "Kurzgesagt/Season 2026/s2026e060101 - Remaining Episode.mp4"
      ),
      "video"
    );

    syncMediaServerShowArtifactsForShowRoot("Kurzgesagt", {
      libraryVideos: [remainingVideo],
    });

    const showNfo = fs.readFileSync(
      path.join(testPaths.videos, "Kurzgesagt/tvshow.nfo"),
      "utf8"
    );
    expect(showNfo).toContain("<premiered>2026-06-01</premiered>");
  });
});
